---
title: "Homework9"
author: "HudsonPlaskoff"
date: "2026-04-02"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(babynames)
```

## Proportion as Percentage^[Question 1 complete]
```{r}
babynames_prop_percent <- babynames %>% 
  mutate(
    prop_percent = str_glue("{str_sub(prop, 4, 4)}.{str_sub(prop, 5, 6)}%")
  )

knitr::kable(babynames_prop_percent %>% head())
```

## Percentage by Year^[Question 2 complete]
```{r}
babynames_prop_percent <- babynames_prop_percent %>% 
  mutate(
    prop_percent_year = str_glue("{str_sub(prop, 4, 4)}.{str_sub(prop, 5, 6)}% in {year}")
  )

knitr::kable(babynames_prop_percent %>% head())
```

## Filter by Name and Sex^[Question 3 complete]
```{r}
babynames_prop_filtered <- babynames_prop_percent %>% 
  filter(
    name=="George",
    sex=="M"
  )

knitr::kable(babynames_prop_filtered %>% head())
```

## Random Rows^[Question 4 complete]
```{r}
set.seed(1)

babynames_sample <- babynames_prop_filtered %>%
  slice_sample(n=5) %>%
  arrange(year)

knitr::kable(babynames_sample %>% head())
```

## Single String^[Question 5 complete]
```{r}
babynames_strings <- babynames_sample %>% pull(prop_percent_year)

babynames_single_string <- str_flatten(babynames_strings,collapse=", ",last=", and ")
  
str_view(babynames_single_string)
```